-- Script : init.lua
require("global")
require("general_settings")
require("plugins")
require("syntax_hightlight")
require("colors")
require("status-line")
require("lsp")
require("custom_finders")
require("git")
